# SERVICE VERSION
info:
  version: @project.version@
# default port
server:
  port: 8092
spring:
  application:
    name: @project.name@
  profiles:
    active: dev
# eureka config
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 30
    service-url.default-zone: http://@rno.registry.host@:8761/eureka
#断路器超时，需与负载均衡超时配合使用，否则将出现多次重复动作
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 40000

ribbon:
  #负载均衡读取超时，应不小于断路器超时
  ReadTimeout: 60000
  #负载均衡连接超时，一般与读取超时相等
  ConnectTimeout: 60000
# After Dalston Release, Feign clients no longer wrap methods in Hystrix commands by default.
feign.hystrix.enabled: true
# mybatis config
mybatis.configuration.mapUnderscoreToCamelCase: true
# log
logging:
  level:
    root: warn
    com.hgicreate.rno.lte: info
    com.hgicreate.rno.lte.mapper: debug
# RNO setting
# job
rno:
  job-type-code: RNO_PCI_AFP_PLAN
  lte-common-service: rno-lte-common-service
  scheduler:
    run-mode: scheduler
    fixed-delay: 10000
  batch: 5000

---

spring:
  profiles: dev
  datasource:
#    url: jdbc:postgresql://192.168.9.66:1949/gpadmin
#    username: gpadmin
#    password: gpadmin
    url: jdbc:postgresql://192.168.9.66:5432/rno_pci
    username: rno_pci
    password: RnoPci@2017
eureka:
  instance:
    metadata-map:
      zone: dev
# log
logging:
  level:
    root: info
    com.hgicreate.rno.lte: debug
    com.hgicreate.rno.lte.mapper: trace